version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: your_user
      DB_PASSWORD: your_password
      DB_NAME: your_database
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: payment_gateway
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  payment-gateway-network:
    driver: bridge

volumes:
  db-volume:
    driver: local
  cache:
    driver: local
