version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - OPPWA_BEARER_TOKEN=your_oppwa_bearer_token
      - SHIFT4_API_KEY=your_shift4_api_key
      - ACI_BASE_URL=https://eu-test.oppwa.com/v1
      - SHIFT4_BASE_URL=https://api.shift4.com
      - PG_DB=payment_gateway
      - PG_USER=root
      - PG_PASSWORD=123456
      - PG_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_URI=postgresql://root:123456@db:5432/payment_gateway
    depends_on:
      - db
      - redis
      - redis
    volumes:
      - .:/usr/src/app
      # No need to mount node_modules if it's managed by Docker
      # - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=payment_gateway
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=payment_gateway
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: